using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OtherLoader.Core.Features.MetaData.Models.Vanilla
{
    public enum SubCategory
    {
        None = 0,
        AutomaticPistol = 1,
        Revolver = 2,
        MachinePistol = 3,
        BreakActionShotgun = 4,
        TubeFedShotgun = 5,
        MagazineFedShotgun = 6,
        SMG = 7,
        PDW = 8,
        LeverActionRifle = 9,
        Carbine = 10,
        AssaultRifle = 11,
        BattleRifle = 12,
        BoltActionRifle = 13,
        AntiMaterial = 14,
        Grenade = 0xF,
        Machinegun = 0x10,
        Ordnance = 17,
        IronSight = 18,
        ReflexSight = 19,
        Magnifier_Scope = 20,
        Suppressor = 21,
        Laser_Light = 22,
        RailAdapter = 23,
        Decorative = 24,
        Tactical = 25,
        Improvised = 26,
        Thrown = 27,
        Utility = 28,
        Target = 29,
        Horseshoe = 30,
        TippyToy = 0x1F,
        Firework = 0x20,
        BreechloadingHandgun = 33,
        LeverActionHandgun = 34,
        LeverActionShotgun = 35,
        Garage = 36,
        PowerTools = 37,
        Medieval = 38,
        GoofyMelee = 39,
        FarmTools = 40,
        Shields = 41,
        BoltActionPistol = 42,
        Foregrip = 43,
        Stock = 44,
        Backpack = 45,
        Bayonet = 46,
        UnderBarrelWeapon = 47,
        BangerJunk = 48,
        RailHat = 49,
        MuzzleLoadedPistol = 50,
        Derringer = 51,
        BreechloadingRifle = 52,
        MuzzleLoadedRifle = 53,
        Bipods = 54,
        MuzzleBrakes = 55,
        MuzzleAdapters = 56,
        Sosigguns = 57,
        GrenadeLaunchers = 58,
        RocketMissileLaunchers = 59,
        LocomotionGuns = 60,
        RemoteExplosives = 61,
        Exotic = 62,
        Barrier = 0x3F,
        SteelTarget = 0x40,
        DestructibleTarget = 65,
        Prop = 66,
        Furniture = 67,
        MF_Scout = 100,
        MF_Soldier = 101,
        MF_Pyro = 102,
        MF_Demo = 103,
        MF_Heavy = 104,
        MF_Engineer = 105,
        MF_Medic = 106,
        MF_Sniper = 107,
        MF_Spy = 108,
        MF_Generic = 109
    }
}
